version: '3'

services:
  api:
    image: hello-dotnet-api-img
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - hello-dotnet-api-network

networks: 
  hello-dotnet-api-network:
      driver: bridge